### ISSUE TITLE
IPinfusuion OCNOS support request 

### ISSUE THREAD

**Issue by traderose** [networktocode/ntc-templates#913]
It would be nice if you can add support for IPinfusuion OCNOS software.

**Comment by jvanderaa** [comment]
@traderose support should be all set. Just need to have templates submitted. Naming will fall in line with the Netmiko naming. `ipinfusion_ocnos` in the same setup that there is `arista_eos`, `cisco_ios`, and `juniper_junos`. 

Looks like there is already a Netmiko driver, so that first part of naming is established.

**Comment by jvanderaa** [comment]
Based on the confidence of the answer and no further response, closing the issue. Feel free to respond and we can reopen if discussion is needed.
