### ISSUE TITLE
Normalize `show arp` Templates

### ISSUE THREAD

**Issue by jvanderaa** [networktocode/ntc-templates#950]
##### ISSUE TYPE

 - Feature Idea

##### TEMPLATE USING

There are 13 different templates that include `show_arp` within the file name. The majority are using `ADDRESS` and `MAC` for keys. We should normalize the remaining to either all be `ADDRESS` and `MAC` or their longer, more explicit form of `IP_ADDRESS` and `MAC_ADDRESS`. This will help to provide normalized templates across vendors.

**Comment by itdependsnetworks** [comment]
Not completely against it, but would need to figure out transition plan and deprecating policy. It is worth noting the following from faq

What is meant that this is a parsing project, not a data modeling project?

The project intends to parse, meaning post processing is assumed in order to normalize the data. This project does not intend to solve that problem set. This is often noted in keys being different between the same command on multiple OS's. This was not intentional as at first there was not strict enforcement. That being said, there is no intention to retrofit this use case for the above stated reasons. This use case is best handled in post processing.

**Comment by itdependsnetworks** [comment]
closing per: https://ntc-templates.readthedocs.io/en/latest/user/faq/#what-is-meant-that-this-is-a-parsing-project-not-a-data-modeling-project
